name = "misub"
main = "functions/[[path]].js"
compatibility_date = "2025-02-04"

# KV 命名空间绑定
# 这是 wrangler.toml 在Pages项目中最重要的作用
[[kv_namespaces]]
binding = "KV"
id = "cf924ed6a93f4ea6a85431d0b51a2130" # 请确保这里是你正确的 KV ID
preview_id = "<ID_OF_PREVIEW_KV_NAMESPACE_FOR_LOCAL_DEVELOPMENT>" # 请确保这里是你正确的预览 KV ID

# 你也可以在这里定义环境变量，但更推荐在Cloudflare控制面板设置
[vars]
ADMIN_PASSWORD = "admin"
COOKIE_SECRET = "a_very_long_random_secret_string"

[triggers]
# "*/30" 表示每30分鐘
# "0 */6 * * *" 表示每6小時
# 根據您的需要調整 cron 表達式
crons = ["0 */6 * * *"] 